### ISSUE TITLE
怎么上拉刷新？

### ISSUE THREAD

**Issue by BeingX** [yuwind/HHRefreshManager#1]
如题

**Comment by yuwind** [comment]
默认是有上拉加载的，如果不需要，设置isNeedFootRefresh=NO即可。
通过代理类型回调，
- (void)beginRefreshWithType:(HHRefreshType)type;

**Comment by BeingX** [comment]
其他框架都是分开的，这个默认都有，还没习惯，哈哈，建议在介绍里加句话说一下这个事情比较好
